//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.11.08 at 11:12:54 PM IST 
//


package com.bignlp.xmlns.person.v1;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Race.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="Race">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="white"/>
 *     &lt;enumeration value="blackOrAfrican"/>
 *     &lt;enumeration value="asian"/>
 *     &lt;enumeration value="american Indian"/>
 *     &lt;enumeration value="native Hawaiian"/>
 *     &lt;enumeration value="latino"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "Race")
@XmlEnum
public enum Race {

    @XmlEnumValue("white")
    WHITE("white"),
    @XmlEnumValue("blackOrAfrican")
    BLACK_OR_AFRICAN("blackOrAfrican"),
    @XmlEnumValue("asian")
    ASIAN("asian"),
    @XmlEnumValue("american Indian")
    AMERICAN_INDIAN("american Indian"),
    @XmlEnumValue("native Hawaiian")
    NATIVE_HAWAIIAN("native Hawaiian"),
    @XmlEnumValue("latino")
    LATINO("latino");
    private final String value;

    Race(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static Race fromValue(String v) {
        for (Race c: Race.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
